<?php

use Officio\Migration\AbstractMigration;

class RecalculateAccountingBalances extends AbstractMigration
{
    public function up()
    {
        // The list of: 'cleared/not cleared', member_id, company_ta_id, a correct amount
        $arrToRecalculate = array(
            array
            (
                'cleared'
            ,
                520
            ,
                2
            ,
                5238.05
            ),

            array
            (
                'not_cleared'
            ,
                520
            ,
                2
            ,
                5238.05
            ),

            array
            (
                'not_cleared'
            ,
                8380
            ,
                105
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                8420
            ,
                105
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                13086
            ,
                154
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                13626
            ,
                195
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                13858
            ,
                16
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                14711
            ,
                187
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                14707
            ,
                105
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                14650
            ,
                194
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                18441
            ,
                235
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                20607
            ,
                239
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                21484
            ,
                406
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                21489
            ,
                406
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                21490
            ,
                405
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                22648
            ,
                406
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                24024
            ,
                406
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                29848
            ,
                203
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                32212
            ,
                203
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                34208
            ,
                232
            ,
                -500
            ),

            array
            (
                'not_cleared'
            ,
                18892
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                35684
            ,
                154
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                36365
            ,
                286
            ,
                30
            ),

            array
            (
                'not_cleared'
            ,
                37293
            ,
                203
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                37810
            ,
                581
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                35129
            ,
                235
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                42458
            ,
                286
            ,
                2550
            ),

            array
            (
                'not_cleared'
            ,
                42556
            ,
                650
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                20682
            ,
                62
            ,
                550
            ),

            array
            (
                'not_cleared'
            ,
                53292
            ,
                286
            ,
                4240
            ),

            array
            (
                'not_cleared'
            ,
                58049
            ,
                752
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                60152
            ,
                804
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                63492
            ,
                281
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                66632
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                38372
            ,
                286
            ,
                1350
            ),

            array
            (
                'not_cleared'
            ,
                63082
            ,
                813
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                71416
            ,
                286
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                80796
            ,
                617
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                84417
            ,
                235
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                84537
            ,
                774
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                85521
            ,
                896
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                95329
            ,
                896
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                94417
            ,
                974
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                96342
            ,
                994
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                94209
            ,
                974
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                94448
            ,
                975
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                100977
            ,
                843
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                116315
            ,
                994
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                63788
            ,
                813
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                118399
            ,
                994
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                122547
            ,
                1084
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                123061
            ,
                1064
            ,
                180
            ),

            array
            (
                'not_cleared'
            ,
                123143
            ,
                1051
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                124769
            ,
                281
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                135494
            ,
                1137
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                139259
            ,
                1182
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                141444
            ,
                1084
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                146857
            ,
                1069
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                151515
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                155204
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                160615
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                160740
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                165979
            ,
                1303
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                165279
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                171532
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                174158
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                182476
            ,
                994
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                182774
            ,
                1338
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                186562
            ,
                994
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                186907
            ,
                813
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                160119
            ,
                1454
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                129478
            ,
                1454
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                191070
            ,
                1483
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                193006
            ,
                300
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                193028
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                195313
            ,
                994
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                196813
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                197526
            ,
                398
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                197640
            ,
                398
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                200277
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                189912
            ,
                968
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                208605
            ,
                968
            ,
                1460.5
            ),

            array
            (
                'not_cleared'
            ,
                214818
            ,
                1302
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                216078
            ,
                1608
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                207329
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                228100
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                181871
            ,
                1301
            ,
                1600
            ),

            array
            (
                'not_cleared'
            ,
                239122
            ,
                232
            ,
                1800
            ),

            array
            (
                'not_cleared'
            ,
                241269
            ,
                1692
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                241325
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                248077
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                251017
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                251636
            ,
                1302
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                254775
            ,
                1768
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                255383
            ,
                968
            ,
                737.5
            ),

            array
            (
                'not_cleared'
            ,
                254887
            ,
                1667
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                257073
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                257901
            ,
                813
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                258452
            ,
                1093
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                262218
            ,
                1557
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                262252
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                266321
            ,
                1579
            ,
                200
            ),

            array
            (
                'not_cleared'
            ,
                267387
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                266027
            ,
                1462
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                271991
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                282396
            ,
                1911
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                284071
            ,
                968
            ,
                150
            ),

            array
            (
                'not_cleared'
            ,
                277249
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                289447
            ,
                1911
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                290347
            ,
                1951
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                290792
            ,
                1951
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                290958
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                277515
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                294874
            ,
                1976
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                299254
            ,
                1854
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                300913
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                307209
            ,
                394
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                300912
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                306215
            ,
                1911
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                309414
            ,
                570
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                305211
            ,
                1911
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                314565
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                315820
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                316380
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                316419
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                298097
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                318502
            ,
                2000
            ,
                1117
            ),

            array
            (
                'not_cleared'
            ,
                319406
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                319935
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                321420
            ,
                2000
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                321953
            ,
                1091
            ,
                2.7200000000003
            ),

            array
            (
                'not_cleared'
            ,
                288763
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                320270
            ,
                1854
            ,
                500
            ),

            array
            (
                'not_cleared'
            ,
                322219
            ,
                1093
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                325044
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                326160
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                331537
            ,
                570
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                331829
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                334032
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                335467
            ,
                1302
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                340163
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                342865
            ,
                968
            ,
                6881.65
            ),

            array
            (
                'not_cleared'
            ,
                348013
            ,
                2195
            ,
                2000
            ),

            array
            (
                'not_cleared'
            ,
                349144
            ,
                1754
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                349770
            ,
                2066
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                352982
            ,
                2066
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                352600
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                352909
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                355453
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                358518
            ,
                1737
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                342744
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                369645
            ,
                1976
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                365552
            ,
                232
            ,
                235
            ),

            array
            (
                'not_cleared'
            ,
                371168
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                372399
            ,
                570
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                373289
            ,
                2088
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                373357
            ,
                2299
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                376324
            ,
                1302
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                375760
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                377493
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                379000
            ,
                804
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                374648
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                379834
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                374186
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                382954
            ,
                2342
            ,
                967.5
            ),

            array
            (
                'not_cleared'
            ,
                392318
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                395643
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                396335
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                399090
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                400174
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                400670
            ,
                2407
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                401099
            ,
                2347
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                401826
            ,
                2413
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                402262
            ,
                2432
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                342759
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                402940
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                403163
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                404959
            ,
                2413
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                405433
            ,
                1916
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                410705
            ,
                1886
            ,
                1000
            ),

            array
            (
                'not_cleared'
            ,
                411495
            ,
                2469
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                408160
            ,
                1091
            ,
                700
            ),

            array
            (
                'not_cleared'
            ,
                414471
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                414807
            ,
                570
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                415121
            ,
                2401
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                417844
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                419594
            ,
                2387
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                423271
            ,
                2400
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                426358
            ,
                2460
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                426442
            ,
                2550
            ,
                0
            ),

            array
            (
                'cleared'
            ,
                427321
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                427321
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                428109
            ,
                2511
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                428963
            ,
                2555
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                438104
            ,
                1886
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                442954
            ,
                2688
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                443340
            ,
                2688
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                445475
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                446378
            ,
                2511
            ,
                2299.5
            ),

            array
            (
                'not_cleared'
            ,
                449863
            ,
                2695
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                452336
            ,
                232
            ,
                1000
            ),

            array
            (
                'not_cleared'
            ,
                454530
            ,
                2328
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                454535
            ,
                2328
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                454712
            ,
                2329
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                454912
            ,
                2710
            ,
                105
            ),

            array
            (
                'not_cleared'
            ,
                456350
            ,
                2503
            ,
                1695
            ),

            array
            (
                'not_cleared'
            ,
                458600
            ,
                2739
            ,
                3000
            ),

            array
            (
                'not_cleared'
            ,
                458905
            ,
                2710
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                458381
            ,
                232
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                462458
            ,
                2503
            ,
                500
            ),

            array
            (
                'not_cleared'
            ,
                458379
            ,
                2718
            ,
                9050
            ),

            array
            (
                'not_cleared'
            ,
                469567
            ,
                2400
            ,
                900
            ),

            array
            (
                'not_cleared'
            ,
                471833
            ,
                2503
            ,
                1695
            ),

            array
            (
                'not_cleared'
            ,
                468677
            ,
                2400
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                474001
            ,
                2847
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                474509
            ,
                2605
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                476678
            ,
                2329
            ,
                1500
            ),

            array
            (
                'not_cleared'
            ,
                478125
            ,
                2901
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                480616
            ,
                2829
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                480773
            ,
                2901
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                481911
            ,
                2886
            ,
                250
            ),

            array
            (
                'not_cleared'
            ,
                482667
            ,
                2886
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                489646
            ,
                2593
            ,
                100
            ),

            array
            (
                'not_cleared'
            ,
                492025
            ,
                2710
            ,
                53
            ),

            array
            (
                'not_cleared'
            ,
                494694
            ,
                2956
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                495286
            ,
                3041
            ,
                0
            ),

            array
            (
                'cleared'
            ,
                1322055
            ,
                3269
            ,
                1050
            ),

            array
            (
                'not_cleared'
            ,
                1322055
            ,
                3269
            ,
                1050
            ),

            array
            (
                'cleared'
            ,
                506814
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                506814
            ,
                1091
            ,
                500
            ),

            array
            (
                'cleared'
            ,
                486125
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                486125
            ,
                1091
            ,
                300
            ),

            array
            (
                'cleared'
            ,
                486123
            ,
                1091
            ,
                0
            ),

            array
            (
                'not_cleared'
            ,
                486123
            ,
                1091
            ,
                0
            ),

        );

        foreach ($arrToRecalculate as $arrRecalculateInfo) {
            $sql = sprintf(
                "UPDATE `members_ta` SET `%s` = %f WHERE member_id = %d AND company_ta_id = %d",
                $arrRecalculateInfo[0] == 'cleared' ? 'sub_total_cleared' : 'sub_total',
                $arrRecalculateInfo[3],
                $arrRecalculateInfo[1],
                $arrRecalculateInfo[2]
            );

            $this->execute($sql);
        }
    }

    public function down()
    {
    }
}