<?php

/**
 * Default error view
 *
 * @author
 * @version
 */

$this->headTitle('Error Page');
$this->placeholder('title')->set($this->title);
?>
    <h1>Error!</h1>
    <p><?= $this->message ?></p>
<?php if (!empty($this->exception)): ?>
    <h2>Exception information:</h2>
    <p>
        <b>Message:</b> <?= $this->exception->getMessage() ?> at <?= $this->exception->getFile(); ?>:<?= $this->exception->getLine(); ?>
    </p>
    <h4>Stack trace:</h4>
    <pre>
    <?= $this->exception->getTraceAsString() ?>
    </pre>
<?php endif ?>