version: '3'
services:
  
  # PHP Service
  app:
    build:
      context: ./officio
      dockerfile: Dockerfile
      args:
        - CLIENT_CONFIG=${CLIENT_CONFIG}
        - GIT_PERSONAL_ACCESS_TOKEN=${GIT_PERSONAL_ACCESS_TOKEN}
        - NPM_PERSONAL_ACCESS_TOKEN=${NPM_PERSONAL_ACCESS_TOKEN}
    image: docker-officio-app:${OFFICIO_VERSION_RELEASE}
    container_name: app
    restart: always
    tty: true
    environment:
      - GIT_PERSONAL_ACCESS_TOKEN=${GIT_PERSONAL_ACCESS_TOKEN}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_OFFICIO_DATABASE=${MYSQL_OFFICIO_DATABASE}
      - MYSQL_OFFICIO_STATISTICS_DATABASE=${MYSQL_OFFICIO_STATISTICS_DATABASE}
      - MYSQL_OFFICIO_HOST=${MYSQL_OFFICIO_HOST}
      - MYSQL_OFFICIO_STATISTICS_HOST=${MYSQL_OFFICIO_STATISTICS_HOST}
      - MYSQL_OFFICIO_PORTS=${MYSQL_OFFICIO_PORTS}
      - APP_URL=${APP_URL}
    working_dir: /var/www
    depends_on:
      - db_officio
      - db_officio_statistics
    env_file:
    - .env
    volumes:
      # - ./officio/app:/var/www - uncomment to point to local
      - officio-web-application:/var/www
      - ./officio/config/.npmrc:/var/www/.npmrc
      - ./officio/config/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./officio/config/global.php:/var/www/config/autoload/global.php
      - ./officio/config/stubs:/var/www/config/autoload/stubs
      - ./officio/config/auth.json:/var/www/auth.json
    networks:
      officio-network:
        ipv4_address: ${OFFICIO_HOST}

  # Apache Service
  webserver:
    build:
        context: ./apache
        dockerfile: Dockerfile
    image:  docker-officio-apache:${APACHE_VERSION_RELEASE}
    container_name: webserver
    restart: always
    tty: true
    depends_on:
      - app
    ports:
      - ${APACHE_HTTP_PORTS}
      - ${APACHE_HTTPS_PORTS}
    volumes:
      - officio-web-application:/var/www
    networks:
      officio-network:
        ipv4_address: ${APACHE_HOST}

  # MySQL Officio Service
  db_officio:
    build:
      context: ./mysql-officio
      dockerfile: Dockerfile
    image: docker-officio-mysql-officio:${MYSQL_OFFICIO_VERSION_RELEASE}
    container_name: mysql-officio
    restart: always
    tty: true
    ports:
      - ${MYSQL_OFFICIO_PORTS}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_OFFICIO_DATABASE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - officio-mysql:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      officio-network:
        ipv4_address: ${MYSQL_OFFICIO_HOST}

   # MySQL Officio Statistics Service
  db_officio_statistics:
    build:
      context: ./mysql-statistics
      dockerfile: Dockerfile
    image: docker-officio-mysql-officio-statistics:${MYSQL_OFFICIO_STATISTICS_VERSION_RELEASE}
    container_name: mysql-officio-statistics
    restart: always
    tty: true
    ports:
      - ${MYSQL_OFFICIO_STATISTICS_PORTS}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_OFFICIO_STATISTICS_DATABASE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - officio-statistics-mysql:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      officio-network:
        ipv4_address: ${MYSQL_OFFICIO_STATISTICS_HOST}

# Docker Networks
networks:
  officio-network:
    name: officio-network
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

# Volumes
volumes:
  officio-mysql:
    name: officio-mysql
    driver: local
  officio-statistics-mysql:
    name: officio-statistics-mysql
    driver: local
  officio-web-application:
    name: officio-web-application
    driver: local

  