<?php
$this->layout()->useExtjs = true;
$this->headLink()->appendStylesheet($this->layout()->topCssUrl . '/main.css');
$this->headScript()->appendFile($this->layout()->jsUrl . '/import-clients.js');
?>
<div id="import-clients-content">
    <h2>Step #4</h2>
    <form action="<?= $this->layout()->baseUrl ?>/import-clients/step3" autocomplete="off" method="POST">
        <input type="hidden" name="file_name" value="<?= $this->fileName ?>"/>
        <input type="hidden" name="import_client_type" value="<?= $this->clientType ?>"/>
        <input type="hidden" name="import_case_type" value="<?= $this->caseType ?>"/>

        <?php foreach ($this->arrExtraFields as $fieldId => $fieldVal): ?>
            <input type='hidden' name='$fieldId' value='$fieldVal'/><br/>
        <?php endforeach; ?>

        <input type="submit" class="buttons" value="<?= $this->translate('<< Go Back') ?>"/>
    </form>

    <br>

    <div style="width:400px; height:17px; border:1px solid grey; background-color:white; text-align:center; position:relative;">
        <span id="import-clients-percent-progress-span" style="position:absolute; z-index:50; left:<?= $this->percent >= 100 ? 30 : 46 ?>%; top:2px; color:<?= $this->percent > 50 ? 'white' : '#006400' ?>;">
            <?= $this->percent ?>% <?= $this->percent >= 100 ? 'Successfully completed!' : '' ?>
        </span>
        <div id="import-clients-percent-progress-div" style="position:absolute; left:0; top:0; height:17px; width:<?= round(400 * $this->percent / 100) ?>px; background-color:#006400; z-index:10;"></div>
    </div>

    <br>

    <div id="import-clients-log">
        <?php if (isset($this->log)): ?>
            <?= $this->log; ?>
        <?php endif; ?>
    </div>

    <?php if (!is_null($this->commandNextPage)): ?>
        <script type='text/javascript'>setTimeout(function () {
                step4(<?= $this->commandNextPage ?>);
            }, 1500);</script>
    <?php endif; ?>
</div>