<?php

use Clients\Service\Clients\Fields;
use Officio\Common\Json;

/** @var Fields $oFields */
$oFields = $this->oFields;

$this->headLink()->appendStylesheet($this->layout()->topCssUrl . '/main.css');
$this->headScript()->appendFile($this->layout()->jsUrl . '/import-clients.js');
$this->headScript()->captureStart();
echo "var arrCaseTemplates = " . Json::encode($this->arrCaseTypes) . ";";
$this->headScript()->captureEnd();

$this->headStyle()->captureStart();
echo '.profile-select { width: 200px; }';
$this->headStyle()->captureEnd();
?>

<div id="import-clients-content">
    <h2>Step #2</h2><br/>
    <div id="step2_container">
        <h3><?= $this->translate('Please select main fields') ?>:</h3><br/>

        <ul style="color:red; font-weight:bold; line-height:18px;">
            <?php if (count($this->global_errors)) foreach ($this->global_errors as $e) { ?>
                <li><?= $e ?></li>
            <?php } ?>
        </ul>

        <form id="form_step3" action="<?= $this->layout()->baseUrl ?>/import-clients/step3" method="POST">
            <div>
                <?php
                foreach ($this->client_profile['groups'] as $group) {
                    foreach ($group['fields'] as $num => $field) {
                        if (!in_array($field['company_field_id'], $this->arrMainFieldsIds)) {
                            continue;
                        }

                        $action = 'add';
                        if (array_key_exists('field-' . $field['field_id'], $this->arrExtraFields)) {
                            $action         = 'edit';
                            $field['value'] = $this->arrExtraFields['field-' . $field['field_id']];
                        }
                        switch ((int)$field['type']) {
                            case 14:
                                echo "<div style='float:left; padding-right:10px;'>" . $oFields->assignedToField($action, 0, $field) . "</div>";
                                break;

                            case 27:
                                echo "<div style='float:left; padding-right:10px;'>" . $oFields->RMAField($action, 0, $field) . "</div>";
                                break;

                            default:
                                break;
                        }
                    }
                }
                ?>
            </div>
            <div style="clear:left;"></div>

            <div style="padding: 10px 0;">
                <label style="font-weight: bold">Client type:</label> <span class="error"> *</span><br/>
                <input type="radio" name="import_client_type" id="import_client_type_ia" value="individual" <?= $this->clientType == 'individual' ? 'checked="checked"' : '' ?>> <label for="import_client_type_ia" style="padding-right: 15px">Individual Client</label>
                <input type="radio" name="import_client_type" id="import_client_type_employer" value="employer" <?= $this->clientType == 'employer' ? 'checked="checked"' : '' ?>> <label for="import_client_type_employer">Employer Client</label>
            </div>

            <div style="padding: 10px 0;">
                <label style="font-weight: bold" for="import_case_type"><?= $this->caseTypeFieldLabel ?>:</label> <span class="error"> *</span><br/>
                <select name="import_case_type" id="import_case_type">
                    <option value=''>-- Please select --</option>
                    <?php
                    foreach ($this->arrCaseTypes as $arrCaseTypeInfo) {
                        if (in_array($this->clientType, $arrCaseTypeInfo['case_template_type_names'])) {
                            echo "<option value='$arrCaseTypeInfo[case_template_id]' " . ($this->caseType == $arrCaseTypeInfo['case_template_id'] ? 'selected="selected"' : '') . ">$arrCaseTypeInfo[case_template_name]</option>";
                        }
                    }
                    ?>
                </select>
            </div>

            <br/>
            <input type="hidden" name="file_name" class="buttons" value="<?= $this->fileName ?>"/>
        </form>

        <form id="form_step1" action="<?= $this->layout()->baseUrl ?>/import-clients/step1" method="POST">
            <input type="hidden" name="file_name" value="<?= $this->fileName ?>"/>
        </form>

        <table style="width: 100%">
            <tr>
                <td style="width: 50%; text-align: right; padding-right: 20px;">
                    <input type="submit" value="<< Go Back" class="buttons" onclick="$('#form_step1').submit();"/>
                <td style="width: 50%; text-align: left;">
                    <input type="submit" value="Next Step >>" class="buttons" onclick="$('#form_step3').submit();"/>
                </td>
            </tr>
        </table>
    </div>
</div>