<table id="<?=$this->tabId?>profile" cellspacing="0" cellpadding="0" width="100%">
<tr>
    <td align="left" width="5" valign="top"><img src="<?=$this->imgUrl('cor-left-top.gif')?>"/></td>
    <td bgcolor="#ffffff" width="100%" class="brbluetop"><img height="1" width="1" src="<?=$this->imgUrl('spacer.gif')?>"/></td>
    <td align="right" width="5" valign="top"><img height="6" width="5" src="<?=$this->imgUrl('cor-right-top.gif')?>"/></td>
</tr>
<tr>
    <td bgcolor="#ffffff" class="brblueleft">&nbsp;</td>
    <td valign="top" class="tablebg">

    <div style="min-height:535px;">
        <div align="left" id="prospectsTabForm-<?=$this->tabId?>"> </div>
        
        <div style="padding:8px;">
            <div id="prospects-result-count" class="prospects-label" style="float:left;"></div>
            <div class="prospects-label" style="float:right;"><?=$this->translate('Click on each entry to view profile')?></div>
        </div>
    </div>

    </td>
    <td bgcolor="#ffffff" class="brblueright">&nbsp;</td>
</tr>
<tr>
    <td align="left" valign="bottom"><img src="<?=$this->imgUrl('cor-left-bottom.gif')?>"/></td>
    <td bgcolor="#ffffff" class="brbluebtm"><img height="1" width="1" src="<?=$this->imgUrl('spacer.gif')?>"/></td>
    <td align="right" valign="bottom"><img src="<?=$this->imgUrl('cor-right-bottom.gif')?>"/></td>
</tr>
</table>
