<html>
<head>
    <title><?=$this->pageTitle?></title>
    <style type="text/css">
        * html body{
            overflow:hidden;
        }

        # html body{
            overflow:hidden;
        }

        * {
            font-family: Arial, Helvetica, sans-serif;
        }

        body {
            padding: 0; margin: 0;
            background-color: #DDE4FF;
            color: #3F6CA2;
        }

        #header {
            padding: 8px;
            text-align: center;
            height: 30px;
        }

        iframe {
            width: 100%;
            height: 100%;
            border: none;
        }
    </style>
</head>
<body>
    <table style="height:100%; width: 100%;" cellpadding="0" cellspacing="0">
        <tr><td id="header"><?=$this->pageTitle?></td></tr>
        <tr><td><iframe src="<?=$this->embedUrl?>" scrolling="no" frameborder="0"></iframe></td></tr>
    </table>
</body>
</html>