<?php
    $this->layout()->useJQuery = true;
    $this->layout()->useExtjs = true;
    $this->headScript()->appendFile($this->layout()->jsUrl . '/generatePasswordButton.js');
    $this->headScript()->appendFile($this->layout()->jsUrl . '/change-my-password/init.js');
    $this->headScript()->appendFile($this->layout()->jsUrl . '/iframe_height.js');

    $bgClass  = '';
    function getBgColor() {
        global $bgClass;
        $bgClass =($bgClass == "evenRow") ? "oddRow" : "evenRow"; 
        return $bgClass;    
    }

    $this->layout()->title = "Change Password";
    $this->headTitle('Change Password');
?>
<?php $this->headStyle()->captureStart() ?>
    .change-password-container td {
        padding: 5px;
    }

    .change-password-container .textbox {
        padding: 3px;
    }
<?php $this->headStyle()->captureEnd();?>

<div class="admin-tab-content">
    <form method="post" action="<?=$this->layout()->baseUrl;?>/change-my-password/update">

        <?php if (!empty($this->message)) echo $this->messageBox($this->message, $this->booError);?>

        <table class="change-password-container" width="70%" border="0" cellpadding="3" cellspacing="1" bgcolor="#D8D8D8" align="center">
            <tr>
                <td class='header_bg header_bg_password' colspan="2" valign="top">Edit Password</td>
            </tr>
            <tr class="blue_text_bold <?=getBgColor()?>">
                <td height="20" width="35%" class="gray_txt" align="right"><B>Username:</B></td>
                <td height="20" width="65%" align="left" class="blue-text1"><B> <?=$this->username; ?> </B></td>
            </tr>
            <tr class="blue_text_bold <?=getBgColor()?>">
                <td height="20" align="right" class="gray_txt"><label for="oldPassword" style="font-weight: bold">Old Password: </label></td>
                <td width="65%" align="left" class="text_11"><input id="oldPassword" name="oldPassword" type="password" class="textbox" size="45"></td>
            </tr>
            <tr class="blue_text_bold <?=getBgColor()?>">
                <td height="20" align="right"  class="gray_txt"><label for="newPassword" style="font-weight: bold">New Password: </label></td>
                <td width="65%" align="left" class="text_11">
                    <input id="newPassword" name="newPassword" style="float: left;" type="text" class="textbox" size="45">
                    <div id="generatePassword" style="float: left; margin-left: 10px"></div>
                </td>
            </tr>
            <tr align="center" class="<?=getBgColor()?>">
                <td  colspan="2" height="20"><input type="submit" class="buttons" value="Update Password"></td>
            </tr>
        </table>
    </form>
</div>