<html>
<head>
  <title><?=$this->translate('Demo requested')?></title>
</head>
<body>

  <h2><?=$this->translate('Demo requested')?></h2>
  
  <table>
    <tr>
      <td><?=$this->translate('Salutation')?></td><td><?=$this->salutation?></td>
    </tr>
    <tr>
      <td><?=$this->translate('Name')?></td><td><?=$this->name?></td>
    </tr>
    <tr>
      <td><?=$this->translate('Last Name')?></td><td><?=$this->last_name?></td>
    </tr>
    <tr>
      <td><?=$this->translate('Company Name')?></td><td><?=$this->company?></td>
    </tr>
    <tr>
      <td><?=$this->translate('Phone (W)')?></td><td><?=$this->phone_w?></td>
    </tr>
    <tr>
      <td><?=$this->translate('Email')?></td><td><?=$this->email?></td>
    </tr>
  </table>
</body>
</html>