<?php

    $this->headLink()->appendStylesheet($this->layout()->topBaseUrl . '/assets/plugins/@fancyapps/fancybox/dist/jquery.fancybox.min.css');
    $this->headScript()->appendFile($this->layout()->topBaseUrl . '/assets/plugins/@fancyapps/fancybox/dist/jquery.fancybox.min.js');

    $this->headScript()->appendFile($this->layout()->topBaseUrl . '/assets/plugins/corejs-typeahead/dist/typeahead.jquery.min.js');
    $this->headScript()->appendFile($this->layout()->topBaseUrl . '/js/help/main.js');
    $this->headScript()->appendFile($this->layout()->topBaseUrl . '/js/help/init.js');
    $this->headLink()->appendStylesheet($this->layout()->topBaseUrl . '/assets/plugins/@fortawesome/fontawesome-free/css/all.min.css');
    $this->headLink()->appendStylesheet($this->layout()->topBaseUrl . '/styles/help.css');

    $faqArrValues = array_values($this->faqArr);
    $arrFirstCategory = empty($this->faqArr) ? array() : array_shift($faqArrValues);
    $this->headScript()->captureStart();
        echo 'var helpType = "help";';
        echo 'var defaultCategoryToOpen = "' . ($arrFirstCategory['faq_section_id'] ?? '') . '";';
    $this->headScript()->captureEnd();

    $this->headStyle()->captureStart();
        echo 'html,body { height: 100%; }';
    $this->headStyle()->captureEnd();

function show_section($faqSection, $level, $topCategoryId)
{
    ?>
    <div class="faq-section-wrap" style="padding-left:<?= ($level - 2) * 20 ?>px;">
        <div class="faq-section-name <?= $level == 1 ? 'level1' : '' ?> <?= $level == 1 || (empty($faqSection['faq']) && (empty($faqSection['subcategories']))) ? '' : 'expandable'?>" style="">
            <?php
                $sectionName = $faqSection['section_name'];
                if (!empty($faqSection['section_class'])) {
                    $sectionName = '<i class="'.$faqSection['section_class'].'"></i>' . $sectionName;
                }
            ?>

            <?php if (!empty($faqSection['section_external_link'])) : ?>
                <a href="<?= $faqSection['section_external_link'] ?>" target="_blank" id="faq-section-id-<?= $faqSection['faq_section_id'] ?>"><?= $sectionName ?></a>
            <?php elseif ($faqSection['section_show_as_heading'] === 'Y') : ?>
                <a href="#c<?= $faqSection['faq_section_id'] ?>" class="faq-section-link faq-section-title <?= $level !== 1 ? ' faq-section-leaf' : '' ?>" id="faq-section-id-<?= $faqSection['faq_section_id'] ?>"><?= $sectionName ?></a>
            <?php else : ?>
                <a href="#c<?= $faqSection['faq_section_id'] ?>" class="faq-section-link <?= $level !== 1 ? ' faq-section-leaf' : '' ?>" id="faq-section-id-<?= $faqSection['faq_section_id'] ?>"><?= $sectionName ?></a>
            <?php endif; ?>
        </div>

        <div class="faq-section-content <?= $faqSection['section_show_as_heading'] === 'Y' ? 'faq-section-content-heading' : '' ?>" <?= $faqSection['section_show_as_heading'] === 'Y' ? '' : 'style="display:none;"' ?> >
            <?php
            if (!empty($faqSection['faq'])) {
                foreach ($faqSection['faq'] as $faq) {
                    show_question($faq, $topCategoryId);
                }
            }

            if (isset($faqSection['subcategories'])) {
                foreach ($faqSection['subcategories'] as $subcat) {
                    show_section($subcat, 2, $topCategoryId);
                }
            }
            ?>
        </div>
    </div>
    <?php
}

function show_question($faq, $topCategoryId)
{
    $href   = empty($topCategoryId) ? '#f' . $faq['faq_id'] : '#q' . $faq['faq_id'];
    $id     = empty($topCategoryId) ? 'faq-featured-question-id-' . $faq['faq_id'] : 'faq-question-id-' . $faq['faq_id'];
    $answer = str_ireplace('<img src', '<img loading="lazy" src', $faq['answer'] ?? '');
    $answer = str_ireplace('<iframe src="https://player.vimeo', '<iframe class="lazyload" data-src="https://player.vimeo', $answer);
    ?>
    <div class="faq">
        <div class="faq-question">
            <a href="<?= $href ?>" category_id="<?= $faq['faq_section_id'] ?>" top_category_id="<?= $topCategoryId ?>" id="<?= $id ?>" class="article-icon-<?= $faq['content_type'] ?>"><?= $faq['question'] ?></a>
        </div>
        <div class="faq-answer faq-hidden">
            <div><?= $answer ?></div>
        </div>
    </div>
    <?php
}

?>

<?php if (empty($this->faqArr)): ?>
    <div class="faq-answer"><i><?= $this->translate('No help articles') ?></i></div>
<?php else: ?>
    <div class="container-fluid h-100" style="max-width: none; padding: 0;">
        <div class="row help-loading" style="margin: 0 auto; padding-top: 80px; width: 210px;"><img src="<?=$this->layout()->topBaseUrl?>/images/loadingAnimation.gif" alt="Loading..." /></div>
        <div class="row h-100 help-content" style="margin: 0; background-color: white; display: none">
            <div class="col-3 sections-container">
                <?php
                foreach ($this->faqArr as $faqSection) {
                    show_section($faqSection, 1, $faqSection['faq_section_id']);
                }
                ?>
            </div>
            <div id="answer_to_question" class="col-9"></div>
        </div>
    </div>
<?php endif; ?>
