INSERT INTO `applicant_types` VALUES (1, 10, 0, 'Sales Agent', 'Y');
INSERT INTO `applicant_types` VALUES (2, 10, 0, 'Legal Practitioner', 'N');
INSERT INTO `applicant_types` VALUES (3, 10, 0, 'Department of Immigration', 'N');
INSERT INTO `applicant_types` VALUES (4, 10, 0, 'State Government', 'N');
INSERT INTO `applicant_types` VALUES (5, 10, 0, 'Regional Body', 'N');
INSERT INTO `applicant_types` VALUES (6, 10, 0, 'Translator', 'N');
INSERT INTO `applicant_types` VALUES (7, 10, 0, 'Education Provider', 'N');
INSERT INTO `applicant_types` VALUES (8, 10, 0, 'Others', 'N');


/* IA blocks */
INSERT INTO `applicant_form_blocks` VALUES (1, 8, 0, NULL, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (2, 8, 0, NULL, 'N', 'N', 1);

/* Employer blocks */
INSERT INTO `applicant_form_blocks` VALUES (3, 7, 0, NULL, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (4, 7, 0, NULL, 'Y', 'Y', 1);
INSERT INTO `applicant_form_blocks` VALUES (5, 7, 0, NULL, 'N', 'Y', 2);
INSERT INTO `applicant_form_blocks` VALUES (6, 7, 0, NULL, 'N', 'Y', 3);
INSERT INTO `applicant_form_blocks` VALUES (7, 7, 0, NULL, 'N', 'Y', 4);
INSERT INTO `applicant_form_blocks` VALUES (8, 7, 0, NULL, 'N', 'Y', 5);

/* Contact blocks */
INSERT INTO `applicant_form_blocks` VALUES (20, 10, 0, 1, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (21, 10, 0, 2, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (22, 10, 0, 3, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (23, 10, 0, 4, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (24, 10, 0, 5, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (25, 10, 0, 6, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (26, 10, 0, 7, 'Y', 'N', 0);
INSERT INTO `applicant_form_blocks` VALUES (27, 10, 0, 8, 'Y', 'N', 0);


ALTER TABLE `applicant_form_blocks` AUTO_INCREMENT = 100;

/* IA groups */
INSERT INTO `applicant_form_groups` VALUES (1, 1, 0, 'Personal Info', 3, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (2, 1, 0, 'Contact Info', 3, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (3, 2, 0, 'Client Login', 3, 'Y', 1);

/* Employer groups */
INSERT INTO `applicant_form_groups` VALUES (4, 3, 0, 'Company Information', 3, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (5, 4, 0, 'Authorized Contacts', 3, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (6, 5, 0, 'Engagements', 3, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (7, 6, 0, 'Other legal entities', 3, 'Y', 3);
INSERT INTO `applicant_form_groups` VALUES (8, 7, 0, 'Other locations', 3, 'Y', 4);
INSERT INTO `applicant_form_groups` VALUES (9, 8, 0, 'Third party contractors', 3, 'Y', 5);

/* Contact groups */
INSERT INTO `applicant_form_groups` VALUES (10, 20, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (11, 20, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (12, 20, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (13, 21, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (14, 21, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (15, 21, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (16, 22, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (17, 22, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (18, 22, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (19, 23, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (20, 23, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (21, 23, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (22, 24, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (23, 24, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (24, 24, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (25, 25, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (26, 25, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (27, 25, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (28, 26, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (29, 26, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (30, 26, 0, 'Notes & Comments', 4, 'Y', 2);
INSERT INTO `applicant_form_groups` VALUES (31, 27, 0, 'Contact Information', 4, 'N', 0);
INSERT INTO `applicant_form_groups` VALUES (32, 27, 0, 'Address & Contact Details', 4, 'Y', 1);
INSERT INTO `applicant_form_groups` VALUES (33, 27, 0, 'Notes & Comments', 4, 'Y', 2);

ALTER TABLE `applicant_form_groups` AUTO_INCREMENT = 100;

/* Internal contact fields */
INSERT INTO `applicant_form_fields` VALUES (1, 9, 0, 'first_name', 'text', 'First Name', 64, 'N', 'Y', 'N', 'Y');
INSERT INTO `applicant_form_fields` VALUES (2, 9, 0, 'last_name', 'text', 'Last Name', 64, 'N', 'Y', 'N', 'Y');
INSERT INTO `applicant_form_fields` VALUES (3, 9, 0, 'phone_h', 'phone', 'Phone (Home)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (4, 9, 0, 'phone_secondary', 'phone', 'Phone (Secondary)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (5, 9, 0, 'phone_main', 'phone', 'Phone (Main)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (6, 9, 0, 'email', 'email', 'Email (Primary)', NULL, 'N', 'N', 'N', 'Y');
INSERT INTO `applicant_form_fields` VALUES (7, 9, 0, 'email_1', 'email', 'Email (Other)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (8, 9, 0, 'contact_type', 'combo', 'Contact type', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (9, 9, 0, 'title', 'combo', 'Salutation', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (10, 9, 0, 'DOB', 'date_repeatable', 'Date of Birth', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (11, 9, 0, 'passport_number', 'text', 'Passport #', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (12, 9, 0, 'passport_exp_date', 'date', 'Passport Expiry Date', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (13, 9, 0, 'country_of_birth', 'text', 'Country of Birth', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (14, 9, 0, 'country_of_residence', 'text', 'Country of Residence', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (15, 9, 0, 'country_of_citizenship', 'text', 'Country of Citizenship', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (16, 9, 0, 'salutation_in_native_lang', 'text', 'Salutation in Native Language', 20, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (17, 9, 0, 'name_in_native_lang', 'text', 'Name in Native Language', 50, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (18, 9, 0, 'preferred_language', 'text', 'Preferred Language', 20, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (19, 9, 0, 'photo', 'photo', 'Photo', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (20, 9, 0, 'address_1', 'text', 'Address 1', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (21, 9, 0, 'address_2', 'text', 'Address 2', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (22, 9, 0, 'city', 'text', 'City', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (23, 9, 0, 'state', 'text', 'Province/State', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (24, 9, 0, 'country', 'text', 'Country', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (25, 9, 0, 'zip_code', 'text', 'Postal/zip code', 16, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (26, 9, 0, 'fax_w', 'phone', 'Fax', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (27, 9, 0, 'pref_contact_method', 'combo', 'Preferred Contact Method', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (28, 9, 0, 'special_instruction', 'memo', 'Special Instruction', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (29, 9, 0, 'entity_name', 'text', 'Entity Name', NULL, 'N', 'Y', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (30, 9, 0, 'company_legal_name', 'text', 'Company Legal Name', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (31, 9, 0, 'company_activity', 'text', 'Company Activity', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (32, 9, 0, 'website', 'text', 'Website', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (33, 9, 0, 'status', 'combo', 'Status', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (34, 9, 0, 'email_2', 'email', 'Email 2', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (35, 9, 0, 'fax_home', 'phone', 'Fax (Home)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (36, 9, 0, 'fax_other', 'phone', 'Fax (Others)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (37, 9, 0, 'notes', 'memo', 'Notes', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (38, 9, 0, 'position', 'text', 'Position', 30, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (39, 9, 0, 'other_names', 'text', 'Other Names', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (40, 9, 0, 'sex', 'combo', 'Sex', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (41, 9, 0, 'relationship_status', 'combo', 'Relationship Status', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (42, 9, 0, 'nationality', 'text', 'Nationality', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (43, 9, 0, 'passport_issuing_authority', 'text', 'Passport Issuing Authority', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (44, 9, 0, 'passport_issue_date', 'date', 'Passport Issue Date', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (45, 9, 0, 'passport_expiry_date', 'date', 'Passport Expiry Date', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (46, 9, 0, 'current_visa', 'text', 'Current Visa', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (47, 9, 0, 'visa_expiry_date', 'date', 'Visa Expiry Date', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (48, 9, 0, 'country_of_passport', 'text', 'Country of Passport', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (49, 9, 0, 'emergency_contact', 'text', 'Emergency Contact', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (50, 9, 0, 'emergency_contact_phone_number', 'phone', 'Emergency Contact Phone Number', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (51, 9, 0, 'department', 'text', 'Department', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (52, 9, 0, 'medical_expiration_date', 'date', 'Medical Expiration Date', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (53, 9, 0, 'migrating', 'combo', 'Migrating', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (54, 9, 0, 'entered_queue_on', 'office_change_date_time', 'Entered Queue On', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (55, 9, 0, 'phone_w', 'phone', 'Phone (Work)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (56, 9, 0, 'phone_m', 'phone', 'Phone (Mobile)', NULL, 'N', 'N', 'N', 'N');

/* IA fields */
INSERT INTO `applicant_form_fields` VALUES (100, 8, 0, 'office', 'office_multi', 'Office', NULL, 'N', 'Y', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (101, 8, 0, 'username', 'text', 'Username', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (102, 8, 0, 'password', 'password', 'Password', 64, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (103, 8, 0, 'disable_login', 'combo', 'Client Login Access', 0, 'N', 'Y', 'N', 'N');

/* Employer fields */
INSERT INTO `applicant_form_fields` VALUES (200, 7, 0, 'company_date_business_started', 'date', 'Date business started', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (201, 7, 0, 'company_cra_business_number', 'text', 'C.R.A. business number', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (202, 7, 0, 'company_number_cdn_employees', 'number', 'Number of Canadian employees', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (203, 7, 0, 'company_number_foreign_employees', 'number', 'Number of foreign employees', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (204, 7, 0, 'company_number_lay_offs', 'number', 'Number lay offs in last 12 months', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (205, 7, 0, 'engagement_number', 'text', 'Engagement #', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (206, 7, 0, 'engagement_name', 'text', 'Engagement name', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (207, 7, 0, 'engagement_description', 'text', 'Engagement description', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (208, 7, 0, 'entity_legal_name', 'text', 'Legal name of entity', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (209, 7, 0, 'entity_legal_name_common', 'text', 'Legal entity name (common use)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (210, 7, 0, 'entity_date_business_started', 'date', 'Date business started', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (211, 7, 0, 'entity_cra_business_number', 'text', 'C.R.A. business number', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (212, 7, 0, 'other_address_line_1', 'text', 'Address line 1', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (213, 7, 0, 'other_address_line_2', 'text', 'Address line 2', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (214, 7, 0, 'other_province', 'text', 'City province/state', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (215, 7, 0, 'other_country', 'text', 'Country', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (216, 7, 0, 'other_postal_code', 'text', 'Postal code', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (217, 7, 0, 'other_city', 'text', 'City', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (218, 7, 0, 'other_number_cdn_employees', 'number', 'Number of Canadian employees', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (219, 7, 0, 'other_number_foreign_employees', 'number', 'Number of foreign employees', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (220, 7, 0, 'other_number_lay_offs', 'number', 'Number lay offs in last 12 months', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (221, 7, 0, 'contractor_legal_company_name_common', 'text', 'Company common name (common use)', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (222, 7, 0, 'contractor_legal_company_name', 'text', 'Legal name of company', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (223, 7, 0, 'contractor_business_type', 'text', 'Type of business', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (224, 7, 0, 'contractor_business_description', 'text', 'Description of business', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (225, 7, 0, 'contractor_date_business_started', 'date', 'Date business started', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (226, 7, 0, 'contractor_address_line_1', 'text', 'Address line 1', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (227, 7, 0, 'contractor_address_line_2', 'text', 'Address line 2', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (228, 7, 0, 'contractor_province', 'text', 'City province/state', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (229, 7, 0, 'contractor_country', 'text', 'Country', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (230, 7, 0, 'contractor_postal_code', 'text', 'Postal code', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (231, 7, 0, 'contractor_city', 'text', 'City', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (232, 7, 0, 'contractor_cra_business_number', 'text', 'C.R.A. business number', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (233, 7, 0, 'contractor_number_cdn_employees', 'number', 'Number of Canadian employees', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (234, 7, 0, 'contractor_number_foreign_employees', 'number', 'Number of foreign employees', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (235, 7, 0, 'contractor_number_lay_offs', 'number', 'Number lay offs in last 12 months', NULL, 'N', 'N', 'N', 'N');
INSERT INTO `applicant_form_fields` VALUES (236, 7, 0, 'office', 'office_multi', 'Our Office', NULL, 'N', 'Y', 'N', 'N');

/* Contact fields */
INSERT INTO `applicant_form_fields` VALUES (237, 10, 0, 'office', 'office_multi', 'Office', NULL, 'N', 'Y', 'N', 'N');


ALTER TABLE `applicant_form_fields` AUTO_INCREMENT = 500;

INSERT INTO `applicant_form_default` VALUES (NULL, 8, 'HR representative', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 8, 'Mobility advisor', 1);
INSERT INTO `applicant_form_default` VALUES (NULL, 8, 'Team lead', 2);
INSERT INTO `applicant_form_default` VALUES (NULL, 8, 'Legal counsel', 3);
INSERT INTO `applicant_form_default` VALUES (NULL, 8, 'Other', 4);

INSERT INTO `applicant_form_default` VALUES (NULL, 9, 'Mr.', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 9, 'Ms.', 1);
INSERT INTO `applicant_form_default` VALUES (NULL, 9, 'Mrs.', 2);
INSERT INTO `applicant_form_default` VALUES (NULL, 9, 'Miss', 3);
INSERT INTO `applicant_form_default` VALUES (NULL, 9, 'Dr.', 4);
INSERT INTO `applicant_form_default` VALUES (NULL, 9, 'Mr. & Mrs.', 5);

INSERT INTO `applicant_form_default` VALUES (NULL, 27, 'Email', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 27, 'Fax', 1);
INSERT INTO `applicant_form_default` VALUES (NULL, 27, 'Phone', 2);

INSERT INTO `applicant_form_default` VALUES (NULL, 33, 'Active', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 33, 'Closed', 1);
INSERT INTO `applicant_form_default` VALUES (NULL, 33, 'Archived', 2);

INSERT INTO `applicant_form_default` VALUES (NULL, 40, 'Male', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 40, 'Female', 1);

INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'Never Married', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'Married', 1);
INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'Engaged', 2);
INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'Widowed', 3);
INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'Separated', 4);
INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'Divorced', 5);
INSERT INTO `applicant_form_default` VALUES (NULL, 41, 'De-Facto/Common Law', 6);

INSERT INTO `applicant_form_default` VALUES (NULL, 53, 'Yes', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 53, 'No', 1);


INSERT INTO `applicant_form_default` VALUES (NULL, 103, 'Enabled', 0);
INSERT INTO `applicant_form_default` VALUES (NULL, 103, 'Disabled', 1);

/***** IA *****/
INSERT INTO `applicant_form_order` VALUES (1, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (1, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (1, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (1, 16, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (1, 17, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (1, 18, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (1, 10, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (1, 40, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (1, 41, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (1, 13, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (1, 14, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (1, 15, 'N', 11);
INSERT INTO `applicant_form_order` VALUES (1, 11, 'N', 12);
INSERT INTO `applicant_form_order` VALUES (1, 48, 'N', 13);
INSERT INTO `applicant_form_order` VALUES (1, 43, 'N', 14);
INSERT INTO `applicant_form_order` VALUES (1, 44, 'N', 15);
INSERT INTO `applicant_form_order` VALUES (1, 12, 'N', 16);
INSERT INTO `applicant_form_order` VALUES (1, 100, 'N', 17);
INSERT INTO `applicant_form_order` VALUES (1, 46, 'N', 18);
INSERT INTO `applicant_form_order` VALUES (1, 47, 'N', 19);
INSERT INTO `applicant_form_order` VALUES (1, 19, 'N', 20);
INSERT INTO `applicant_form_order` VALUES (2, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (2, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (2, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (2, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (2, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (2, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (2, 55, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (2, 3, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (2, 56, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (2, 6, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (2, 7, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (2, 26, 'N', 11);
INSERT INTO `applicant_form_order` VALUES (2, 27, 'N', 12);
INSERT INTO `applicant_form_order` VALUES (2, 28, 'N', 13);
INSERT INTO `applicant_form_order` VALUES (3, 101, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (3, 102, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (3, 103, 'N', 2);

/***** Employer *****/
INSERT INTO `applicant_form_order` VALUES (4, 29, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (4, 30, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (4, 31, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (4, 236, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (4, 20, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (4, 21, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (4, 22, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (4, 23, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (4, 24, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (4, 25, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (4, 4, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (4, 5, 'N', 11);
INSERT INTO `applicant_form_order` VALUES (4, 26, 'N', 12);
INSERT INTO `applicant_form_order` VALUES (4, 32, 'N', 13);
INSERT INTO `applicant_form_order` VALUES (4, 200, 'N', 14);
INSERT INTO `applicant_form_order` VALUES (4, 201, 'N', 15);
INSERT INTO `applicant_form_order` VALUES (4, 202, 'N', 16);
INSERT INTO `applicant_form_order` VALUES (4, 203, 'N', 17);
INSERT INTO `applicant_form_order` VALUES (4, 204, 'N', 18);
INSERT INTO `applicant_form_order` VALUES (5, 5, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (5, 4, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (5, 6, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (5, 7, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (5, 8, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (6, 205, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (6, 206, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (6, 207, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (7, 208, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (7, 209, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (7, 210, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (7, 211, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (8, 212, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (8, 213, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (8, 214, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (8, 215, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (8, 216, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (8, 217, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (8, 218, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (8, 219, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (8, 220, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (9, 221, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (9, 222, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (9, 223, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (9, 224, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (9, 225, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (9, 226, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (9, 227, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (9, 228, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (9, 229, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (9, 230, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (9, 231, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (9, 232, 'N', 11);
INSERT INTO `applicant_form_order` VALUES (9, 233, 'N', 12);
INSERT INTO `applicant_form_order` VALUES (9, 234, 'N', 13);
INSERT INTO `applicant_form_order` VALUES (9, 235, 'N', 14);

/***** Contact *****/
INSERT INTO `applicant_form_order` VALUES (10, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (10, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (10, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (10, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (10, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (10, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (11, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (11, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (11, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (11, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (11, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (11, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (11, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (11, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (11, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (11, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (11, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (12, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (13, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (13, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (13, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (13, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (13, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (13, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (14, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (14, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (14, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (14, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (14, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (14, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (14, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (14, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (14, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (14, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (14, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (15, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (16, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (16, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (16, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (16, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (16, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (16, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (17, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (17, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (17, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (17, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (17, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (17, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (17, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (17, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (17, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (17, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (17, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (18, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (19, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (19, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (19, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (19, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (19, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (19, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (20, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (20, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (20, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (20, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (20, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (20, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (20, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (20, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (20, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (20, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (20, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (21, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (22, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (22, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (22, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (22, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (22, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (22, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (23, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (23, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (23, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (23, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (23, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (23, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (23, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (23, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (23, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (23, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (23, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (24, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (25, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (25, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (25, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (25, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (25, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (25, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (26, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (26, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (26, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (26, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (26, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (26, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (26, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (26, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (26, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (26, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (26, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (27, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (28, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (28, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (28, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (28, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (28, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (28, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (29, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (29, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (29, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (29, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (29, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (29, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (29, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (29, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (29, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (29, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (29, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (30, 37, 'Y', 1);
INSERT INTO `applicant_form_order` VALUES (31, 9, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (31, 1, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (31, 2, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (31, 38, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (31, 51, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (31, 237, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (32, 20, 'N', 0);
INSERT INTO `applicant_form_order` VALUES (32, 21, 'N', 1);
INSERT INTO `applicant_form_order` VALUES (32, 22, 'N', 2);
INSERT INTO `applicant_form_order` VALUES (32, 23, 'N', 3);
INSERT INTO `applicant_form_order` VALUES (32, 24, 'N', 4);
INSERT INTO `applicant_form_order` VALUES (32, 25, 'N', 5);
INSERT INTO `applicant_form_order` VALUES (32, 5, 'N', 6);
INSERT INTO `applicant_form_order` VALUES (32, 4, 'N', 7);
INSERT INTO `applicant_form_order` VALUES (32, 6, 'N', 8);
INSERT INTO `applicant_form_order` VALUES (32, 7, 'N', 9);
INSERT INTO `applicant_form_order` VALUES (32, 26, 'N', 10);
INSERT INTO `applicant_form_order` VALUES (33, 37, 'Y', 1);
