DROP TABLE `acal_calendars`;
DROP TABLE `acal_cron_runs`;
DROP TABLE `acal_eventrepeats`;
DROP TABLE `acal_events`;
DROP TABLE `acal_exclusions`;
DROP TABLE `acal_publications`;
DROP TABLE `acal_reminders`;
DROP TABLE `acal_sharing`;
DROP TABLE `acal_users_data`;
TRUNCATE `access_logs`;
--TRUNCATE `acl_modules`;
DELETE FROM `acl_roles` WHERE `company_id` != 0;
--TRUNCATE `acl_role_access`;
--TRUNCATE `acl_rules`;
--TRUNCATE `acl_rule_details`;
DROP TABLE `admin_navigation`;
DROP TABLE `admin_navigation_sections`;
TRUNCATE `agents`;
DELETE FROM `applicant_form_blocks` WHERE `company_id` != 0;
TRUNCATE `applicant_form_data`;
--TRUNCATE `applicant_form_default`;
DELETE FROM `applicant_form_fields` WHERE `company_id` != 0;
--TRUNCATE `applicant_form_fields_access`;
--TRUNCATE `applicant_form_groups`;
--TRUNCATE `applicant_form_order`;
DELETE FROM `applicant_types` WHERE `company_id` != 0;
--TRUNCATE `automated_billing_blacklist`;
TRUNCATE `automated_billing_log`;
DELETE FROM `automated_billing_log_sessions`;
DELETE FROM `automatic_reminders` WHERE `company_id` != 0;
TRUNCATE `automatic_reminders_processed`;
DROP TABLE `awm_accounts`;
DROP TABLE `awm_addr_book`;
DROP TABLE `awm_addr_groups`;
DROP TABLE `awm_addr_groups_contacts`;
DROP TABLE `awm_columns`;
DROP TABLE `awm_domains`;
DROP TABLE `awm_filters`;
DROP TABLE `awm_folders`;
DROP TABLE `awm_folders_tree`;
DROP TABLE `awm_messages_body`;
DROP TABLE `awm_reads`;
DROP TABLE `awm_senders`;
DROP TABLE `awm_settings`;
DROP TABLE `awm_temp`;
DROP TABLE `a_users`;
TRUNCATE `clients`;
TRUNCATE `clients_import`;
TRUNCATE `client_form_data`;
--TRUNCATE `client_form_default`;
--TRUNCATE `client_form_dependents`;
DELETE FROM `client_form_fields` WHERE `company_id` != 0;
--TRUNCATE `client_form_field_access`;
DELETE FROM `client_form_groups` WHERE `company_id` != 0;
--TRUNCATE `client_form_group_access`;
--TRUNCATE `client_form_order`;
DELETE FROM `client_types` WHERE `company_id` != 0;
--TRUNCATE `client_types_kinds`;
--TRUNCATE `company_cmi`;
--TRUNCATE `company_details`;
TRUNCATE `company_invoice`;
--TRUNCATE `company_packages`;
DELETE FROM `company_prospects`;
--TRUNCATE `company_prospects_categories`;
TRUNCATE `company_prospects_data`;
TRUNCATE `company_prospects_data_categories`;
TRUNCATE `company_prospects_job`;
--TRUNCATE `company_prospects_noc`;
--TRUNCATE `company_prospects_noc_job_titles`;
TRUNCATE `company_prospects_notes`;
DELETE FROM `company_prospects_selected_categories` WHERE `company_id` != 0;
DELETE FROM `company_prospects_templates` WHERE `company_id` != 0;
DELETE FROM `company_questionnaires` WHERE `company_id` != 0;
--TRUNCATE `company_questionnaires_category_template`;
--TRUNCATE `company_questionnaires_fields`;
--TRUNCATE `company_questionnaires_fields_custom_options`;
--TRUNCATE `company_questionnaires_fields_options`;
--TRUNCATE `company_questionnaires_fields_options_templates`;
--TRUNCATE `company_questionnaires_fields_templates`;
--TRUNCATE `company_questionnaires_sections`;
--TRUNCATE `company_questionnaires_sections_templates`;
DELETE FROM `company_ta`;
--TRUNCATE `company_trial`;
--TRUNCATE `company_types`;
TRUNCATE `company_websites`;
--TRUNCATE `company_websites_templates`;
--TRUNCATE `country_master`;
TRUNCATE `default_searches`;
--TRUNCATE `divisions`;
TRUNCATE `eml_accounts`;
TRUNCATE `eml_attachments`;
TRUNCATE `eml_deleted_messages`;
DELETE FROM `eml_folders`;
DELETE FROM `eml_messages`;
TRUNCATE `faq`;
TRUNCATE `faq_sections`;
--TRUNCATE `folder_access`;
DELETE FROM `FormAssigned`;
--TRUNCATE `FormFolder`;
--TRUNCATE `FormLanding`;
--TRUNCATE `FormMap`;
--TRUNCATE `FormProcessed`;
--TRUNCATE `FormRevision`;
--TRUNCATE `FormSynField`;
--TRUNCATE `FormTemplates`;
TRUNCATE `FormUpload`;
TRUNCATE `form_default`;
DELETE FROM `FormVersion`;
--TRUNCATE `hst_companies`;
--TRUNCATE `hst_officio`;
TRUNCATE `members_divisions`;
TRUNCATE `members_last_access`;
TRUNCATE `members_relations`;
--TRUNCATE `members_roles`;
TRUNCATE `members_ta`;
--TRUNCATE `members_types`;
DELETE FROM `members` WHERE `company_id` != 0;
TRUNCATE `news`;
--TRUNCATE `packages`;
--TRUNCATE `packages_details`;
TRUNCATE `prospects`;
--TRUNCATE `provincial_hst_rate`;
TRUNCATE `reconciliation_log`;
--TRUNCATE `rss_black_list`;
DELETE FROM `searches` WHERE `company_id` != 0;
--TRUNCATE `superadmin_searches`;
--TRUNCATE `superadmin_smtp`;
--TRUNCATE `system_templates`;
--TRUNCATE `templates`;
TRUNCATE `time_tracker`;
--TRUNCATE `users`;
--TRUNCATE `usertypes`;
--TRUNCATE `user_smtp`;
TRUNCATE `u_assigned_deposits`;
TRUNCATE `u_assigned_withdrawals`;
DELETE FROM `u_deposit_types` WHERE `company_id` != 0;
TRUNCATE `u_destination_types`;
DELETE FROM `u_folders` WHERE `company_id` != 0 AND company_id IS NOT NULL;
TRUNCATE `u_import_transactions`;
DELETE FROM `u_invoice`;
TRUNCATE `u_links`;
TRUNCATE `u_log`;
TRUNCATE `u_notes`;
TRUNCATE `u_payment`;
DELETE FROM `u_payment_schedule`;
TRUNCATE `u_payment_templates`;
TRUNCATE `u_sms`;
DELETE FROM `u_tasks`;
--TRUNCATE `u_tasks_assigned_to`;
--TRUNCATE `u_tasks_messages`;
--TRUNCATE `u_tasks_priority`;
--TRUNCATE `u_tasks_read`;
DELETE FROM `u_trust_account`;
--TRUNCATE `u_variable`;
DELETE FROM `u_withdrawal_types` WHERE `company_id` != 0;
DELETE FROM `company` WHERE `company_id` != 0;